service: hms-api

plugins:
  - serverless-plugin-typescript
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages: [ local ]
    autostart: true
    lambda:
      mountCode: false
    docker:
      sudo: false

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    HACKATHON_TABLE_NAME: hackathon
    CATEGORY_TABLE_NAME: category
    CATEGORY_BY_HACKATHON_ID_INDEX_NAME: by-hackathonId
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.HACKATHON_TABLE_NAME}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CATEGORY_TABLE_NAME}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CATEGORY_TABLE_NAME}/index/*

functions:
  createHackathon:
    handler: src/handlers/hackathon/create.create
    events:
      - http:
          path: hackathon
          method: post
          cors: true
  listAllHackathons:
    handler: src/handlers/hackathon/list.list
    events:
      - http:
          path: hackathons
          method: get
          cors: true
  getHackathon:
    handler: src/handlers/hackathon/get.get
    events:
      - http:
          path: hackathon/{id}
          method: get
          cors: true
  deleteHackathon:
    handler: src/handlers/hackathon/remove.remove
    events:
      - http:
          path: hackathon/{id}
          method: delete
          cors: true

  createIdea:
    handler: src/handlers/idea/create.create
    events:
      - http:
          path: idea
          method: post
          cors: true
  listAllIdea:
    handler: src/handlers/idea/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/ideas
          method: get
          cors: true
  getIdea:
    handler: src/handlers/idea/get.get
    events:
      - http:
          path: idea/{id}
          method: get
          cors: true
  deleteIdea:
    handler: src/handlers/idea/remove.remove
    events:
      - http:
          path: idea/{id}
          method: delete
          cors: true

  createUser:
    handler: src/handlers/user/create.create
    events:
      - http:
          path: user
          method: post
          cors: true
  listAllUser:
    handler: src/handlers/user/list.list
    events:
      - http:
          path: users
          method: get
          cors: true
  getUser:
    handler: src/handlers/user/get.get
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  deleteUser:
    handler: src/handlers/user/remove.remove
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  createParticipant:
    handler: src/handlers/participant/create.create
    events:
      - http:
          path: participant
          method: post
          cors: true
  listAllParticipant:
    handler: src/handlers/participant/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/participants
          method: get
          cors: true
  getParticipant:
    handler: src/handlers/participant/get.get
    events:
      - http:
          path: participant/{id}
          method: get
          cors: true
  deleteParticipant:
    handler: src/handlers/participant/remove.remove
    events:
      - http:
          path: participant/{id}
          method: delete
          cors: true

  createCategory:
    handler: src/handlers/category/create.create
    events:
      - http:
          path: category
          method: post
          cors: true
  listAllCategory:
    handler: src/handlers/category/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/categories
          method: get
          cors: true
  getCategory:
    handler: src/handlers/category/get.get
    events:
      - http:
          path: category/{id}
          method: get
          cors: true
  deleteCategory:
    handler: src/handlers/category/remove.remove
    events:
      - http:
          path: category/{id}
          method: delete
          cors: true

  createSkill:
    handler: src/handlers/skill/create.create
    events:
      - http:
          path: skill
          method: post
          cors: true
  listAllSkill:
    handler: src/handlers/skill/list.list
    events:
      - http:
          path: skills
          method: get
          cors: true
  getSkill:
    handler: src/handlers/skill/get.get
    events:
      - http:
          path: skill/{name}
          method: get
          cors: true
  deleteSkill:
    handler: src/handlers/skill/remove.remove
    events:
      - http:
          path: skill/{name}
          method: delete
          cors: true

resources:
  Resources:
    hackathonTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.HACKATHON_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    categoryTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.CATEGORY_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: hackathonId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.CATEGORY_BY_HACKATHON_ID_INDEX_NAME}
            KeySchema:
              - AttributeName: hackathonId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL
