service: hms-api

plugins:
  - serverless-plugin-typescript
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages: [ local ]
    autostart: true
    lambda:
      mountCode: false
    docker:
      sudo: false

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    HACKATHON_TABLE: hackathon
    USER_TABLE: user
    SKILL_TABLE: skill
    CATEGORY_TABLE: category
    CATEGORY_BY_HACKATHON_ID_INDEX: category-by-hackathonId
    IDEA_TABLE: idea
    IDEA_BY_HACKATHON_ID_INDEX: idea-by-hackathonId
    IDEA_BY_CATEGORY_ID_INDEX: idea-by-categoryId
    IDEA_BY_OWNER_ID_INDEX: idea-by-ownerId
    PARTICIPANT_TABLE: participant
    PARTICIPANT_BY_HACKATHON_ID_INDEX: participant-by-hackathonId
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.HACKATHON_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SKILL_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CATEGORY_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CATEGORY_TABLE}/index/*
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.IDEA_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.IDEA_TABLE}/index/*
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PARTICIPANT_TABLE}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PARTICIPANT_TABLE}/index/*

functions:
  createHackathon:
    handler: src/handler/hackathon/create.create
    events:
      - http:
          path: hackathon
          method: post
          cors: true
  listAllHackathons:
    handler: src/handler/hackathon/list.list
    events:
      - http:
          path: hackathons
          method: get
          cors: true
  getHackathon:
    handler: src/handler/hackathon/get.get
    events:
      - http:
          path: hackathon/{id}
          method: get
          cors: true
  deleteHackathon:
    handler: src/handler/hackathon/remove.remove
    events:
      - http:
          path: hackathon/{id}
          method: delete
          cors: true

  createIdea:
    handler: src/handler/idea/create.create
    events:
      - http:
          path: idea
          method: post
          cors: true
  listAllIdea:
    handler: src/handler/idea/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/ideas
          method: get
          cors: true
  getIdea:
    handler: src/handler/idea/get.get
    events:
      - http:
          path: idea/{id}
          method: get
          cors: true
  deleteIdea:
    handler: src/handler/idea/remove.remove
    events:
      - http:
          path: idea/{id}
          method: delete
          cors: true

  createUser:
    handler: src/handler/user/create.create
    events:
      - http:
          path: user
          method: post
          cors: true
  listAllUser:
    handler: src/handler/user/list.list
    events:
      - http:
          path: users
          method: get
          cors: true
  getUser:
    handler: src/handler/user/get.get
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  deleteUser:
    handler: src/handler/user/remove.remove
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  createParticipant:
    handler: src/handler/participant/create.create
    events:
      - http:
          path: participant
          method: post
          cors: true
  listAllParticipant:
    handler: src/handler/participant/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/participants
          method: get
          cors: true
  getParticipant:
    handler: src/handler/participant/get.get
    events:
      - http:
          path: participant/{id}
          method: get
          cors: true
  deleteParticipant:
    handler: src/handler/participant/remove.remove
    events:
      - http:
          path: participant/{id}
          method: delete
          cors: true

  createCategory:
    handler: src/handler/category/create.create
    events:
      - http:
          path: category
          method: post
          cors: true
  listAllCategory:
    handler: src/handler/category/list.list
    events:
      - http:
          path: hackathon/{hackathonId}/categories
          method: get
          cors: true
  getCategory:
    handler: src/handler/category/get.get
    events:
      - http:
          path: category/{id}
          method: get
          cors: true
  deleteCategory:
    handler: src/handler/category/remove.remove
    events:
      - http:
          path: category/{id}
          method: delete
          cors: true

  createSkill:
    handler: src/handler/skill/create.create
    events:
      - http:
          path: skill
          method: post
          cors: true
  listAllSkill:
    handler: src/handler/skill/list.list
    events:
      - http:
          path: skills
          method: get
          cors: true
  getSkill:
    handler: src/handler/skill/get.get
    events:
      - http:
          path: skill/{id}
          method: get
          cors: true
  deleteSkill:
    handler: src/handler/skill/remove.remove
    events:
      - http:
          path: skill/{id}
          method: delete
          cors: true

resources:
  Resources:
    hackathonTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.HACKATHON_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    userTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    skillTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SKILL_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    categoryTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.CATEGORY_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: hackathonId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.CATEGORY_BY_HACKATHON_ID_INDEX}
            KeySchema:
              - AttributeName: hackathonId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL

    ideaTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.IDEA_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: hackathonId
            AttributeType: S
          - AttributeName: categoryId
            AttributeType: S
          - AttributeName: ownerId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.IDEA_BY_HACKATHON_ID_INDEX}
            KeySchema:
              - AttributeName: hackathonId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.IDEA_BY_CATEGORY_ID_INDEX}
            KeySchema:
              - AttributeName: categoryId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.IDEA_BY_OWNER_ID_INDEX}
            KeySchema:
              - AttributeName: ownerId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL

    participantTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.PARTICIPANT_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: hackathonId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.PARTICIPANT_BY_HACKATHON_ID_INDEX}
            KeySchema:
              - AttributeName: hackathonId
                KeyType: HASH
              - AttributeName: id
                KeyType: RANG
            Projection:
              ProjectionType: ALL
