service: hms-api

plugins:
  - serverless-plugin-typescript
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages: [ local ]
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode: false
    docker:
      sudo: false

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  environment:
    HACKATHON_TABLE: hackathon
    IDEA_TABLE: idea
    USER_TABLE: user
    CATEGORY_TABLE: category
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.HACKATHON_TABLE}'
            - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.IDEA_TABLE}'
            - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_TABLE}'
            - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CATEGORY_TABLE}'

functions:
  createHackathon:
    handler: src/hackathon/create.create
    events:
      - http:
          path: hackathon
          method: post
          cors: true

  listAllHackathons:
    handler: src/hackathon/list.list
    events:
      - http:
          path: hackathons
          method: get
          cors: true

  getHackathon:
    handler: src/hackathon/get.get
    events:
      - http:
          path: hackathon/{id}
          method: get
          cors: true

  deleteHackathon:
    handler: src/hackathon/remove.remove
    events:
      - http:
          path: hackathon/{id}
          method: delete
          cors: true

  createIdea:
    handler: src/idea/create.create
    events:
      - http:
          path: idea
          method: post
          cors: true

  listAllIdea:
    handler: src/idea/list.list
    events:
      - http:
          path: hackathon/{id}/ideas
          method: get
          cors: true

  getIdea:
    handler: src/idea/get.get
    events:
      - http:
          path: idea/{id}
          method: get
          cors: true

  deleteIdea:
    handler: src/idea/remove.remove
    events:
      - http:
          path: idea/{id}
          method: delete
          cors: true

  createUser:
    handler: src/user/create.create
    events:
      - http:
          path: user
          method: post
          cors: true

  listAllUser:
    handler: src/user/list.list
    events:
      - http:
          path: users
          method: get
          cors: true

  getUser:
    handler: src/user/get.get
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  deleteUser:
    handler: src/user/remove.remove
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  createCategory:
    handler: src/category/create.create
    events:
      - http:
          path: category
          method: post
          cors: true

  listAllCategory:
    handler: src/category/list.list
    events:
      - http:
          path: hackathon/{id}/categories
          method: get
          cors: true

  getCategory:
    handler: src/category/get.get
    events:
      - http:
          path: category/{id}
          method: get
          cors: true

  deleteCategory:
    handler: src/category/remove.remove
    events:
      - http:
          path: category/{id}
          method: delete
          cors: true

resources:
  Resources:
    HackathonsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: hackathon
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    IdeasDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: idea
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    CategoriesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: category
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: user
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
